### PR TITLE
feat: build and upload shorebird linker

### PR DESCRIPTION
**Pull request by felangel**
feat: upload shorebird linker

### CODE REVIEW

**Review by bryanoltman — COMMENTED** [review]
The `compile` step should probably go in the build script, no?

**Comment by felangel** [comment]
> The `compile` step should probably go in the build script, no?

I thought the build script was just building the engine and this is independent of that. Happy to move it though just seemed like it would be a bit uglier if we split it because the build script would need to put this file somewhere predictable so that the upload could reliably find it. Let me know what you think

**Comment by bryanoltman** [comment]
The build script creates gen_snapshot (and soon analyze_snapshot) as well. I'd be surprised if 1) build didn't actually build everything and 2) if upload did something other than uploading

**Review by eseidel — APPROVED** [review]

**Comment by felangel** [comment]
> The build script creates gen_snapshot (and soon analyze_snapshot) as well. I'd be surprised if 1) build didn't actually build everything and 2) if upload did something other than uploading

Updated ✅

**Review by bryanoltman — APPROVED** [review]

**Pull request merged**
